default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sourlemon_development

test:
  <<: *default
  database: sourlemon_test

production:
  <<: *default
  database: sourlemon_production
