# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d246b77ad6961f4ccd2ce58d2d13630ba03622eff4c08b9de9d603c22f9d15c1128e4238b99cc3e51b40ee69084fe00c3a1e8133eb760b6ffa93b32ae771715c
  google_analytics_uid: DEV_GAUID
  images_url: https://dl.dropboxusercontent.com/u/4211378/Blog%20Assets

test:
  secret_key_base: 06e96dd670773785984dfa92aa0ceedc8b8a08aa63606cb748fae889b71be55b2c37db3dd69db9ce821030344526d13379bc5bb0376f39266c943f7b937bf919
  google_analytics_uid: TEST_GAUID
  images_url: http://www.example.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_analytics_uid: <%= ENV["GA_UID"] %>
  images_url: https://dl.dropboxusercontent.com/u/4211378/Blog%20Assets
